### ISSUE TITLE
Download functionality errors when specifying custom paths

### ISSUE THREAD

**Issue by vexx32** [test-kitchen/kitchen-pester#53]
# Version:

0.11.0

# Environment:

Mac OS Catalina, running kitchen-pester against a WIndows image over `kitchen-ec2`.

# Scenario:

Downloading additional auxiliary log files that are generated during the verify action.

# Steps to Reproduce:

Run any `kitchen-pester` verify step with config similar to the following:

```yaml
verifier:
  name: pester
  downloads:
    "./PesterTestResults.xml": "./testresults" # attempt to retain the default download setting
    "C:/SomePath/Logs/": "./logs"
```

# Expected Result:

Both the Pester results file and any files in the targeted folder are downloaded to the machine running `kitchen verify`

# Actual Result:

An error is generated:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined method `each' for :"./PesterTestResults.xml":Symbol] on ccm-tests-windows-2019
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

This is the case because our default configuration has a different structure, namely it specifies a dictionary with a single key/value pair where the key itself is an array value, which _cannot_ be defined in yaml.

https://github.com/test-kitchen/kitchen-pester/blob/35f8e1cc427aeeed6729c75e4de440341087e57a/lib/kitchen/verifier/pester.rb#L37

We need to improve our processing of user-defined configuration items, and potentially adjust the default config to at least provide a default value that can be defined in some way in YAML.
