### ISSUE TITLE
Add the ability to pass environment variables through configuration options

### ISSUE THREAD

**Issue by corbob** [test-kitchen/kitchen-pester#82]
## :frowning_person: Problem Statement

We have a need to use API Keys in Pester tests inside of Test Kitchen. Thus, would like the ability to specify the environment variable name and it's desired value in the configuration file to allow our CI systems to use the API key without it being in the actual test code.

## :grey_question: Possible Solution

Take the below configuration:

```yaml
verifier:
  name: pester
  copy_folders:
    - ./test/helpers
  env_variables:
    API_KEY: SomeKey
    REPO_PATH: SomePath
```

Ideally this would create environment variables:

```powershell
$env:API_KEY -eq 'SomeKey'
$env:REPO_PATH -eq 'SomePath
```

## :arrow_heading_up: Describe alternatives you've considered

Have tried setting the API Key other ways during the `kitchen converge` stage, but this doesn't allow us to use it directly in the pester tests, we must store it somewhere that we then retrieve it from.
